# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='delivery_zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
