# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160327_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
